### ISSUE TITLE
sunspot example - warning message

### ISSUE THREAD

**Issue by tomaszek0** [fakenmc/micompr-examples#3]
Execution of the sunspot example script terminates with a warning message:
Warning message:
In the command "wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...)":
     you cannot calculate an exact probability value for repeated values
(R.4.3.1; micompr 1.1.4; Win10)

**Comment by nunofachada** [comment]
Hi, thanks for the feedback. However, on R 4.3.2 / Ubuntu, I'm not getting any warnings with the [sunspot](https://github.com/nunofachada/micompr-examples/blob/master/sunspot.R) example:

![image](https://github.com/nunofachada/micompr-examples/assets/3018963/dc1a028f-993a-4e9b-8aa7-76a166992f17)

Note that the warnings you mentioned can happen in the Mann-Whitney test (i.e. [`wilcox.test()`](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/wilcox.test)) when there are repeated values, so these warning are to be expected if that is the case. Micompr will give you the results anyway, but you need to consider their validity when the associated test yields these types of warning.
